[package]
name = "cartgo"
version = "0.1.0"
edition = "2024"

[lib]
name = "cartgo"
path = "src/lib.rs"

[[bin]]
name = "cartgo"
path = "src/main.rs"

[dependencies]
dialoguer = { version = "0.12.0", default-features = false }
gltf = { version = "1.4.1", features = ["KHR_lights_punctual", "KHR_materials_transmission", "KHR_materials_emissive_strength", "KHR_materials_ior"] }
indicatif = "0.17"
minifb = "0.28.0"

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"

[profile.dev]
opt-level = 2
